elm-street.cabal, src/Elm.hs, src/Elm/Ast.hs, src/ElmStreet.hs
Resolves #2 
I'm not sure how precise these data types describe what we want and how easy it will be to convert from Haskell generic representation to these data types. But that's the first idea. Here we're on Programming Language Theory land and there people use a lot of crazy tricks, the architecture design space is too broad...
=> [#2] Implement AST

.travis.yml, stack.yaml
=> [#12] Add Travis CI config

elm-street.cabal, src/Elm.hs, src/Elm/Ast.hs, src/Elm/Generic.hs
Resolves #7 
Heh, that was painful. But I was mostly copy-pasting from `elm-export`. This is a very first implementation, will be improved over time.
=> [#7] Implement generic conversion

elm-street.cabal, src/Elm.hs, src/Elm/Print.hs
=> [#3] Implement prettyShowDefinition

.ghci, src/Elm/Ast.hs, src/Elm/Print.hs
=> [#4] Implement pretty enum functions

src/Elm/Ast.hs, src/Elm/Generic.hs, src/Elm/Print.hs
Resolves #18 
It works. But currently there's one problem: `()` are not added when types have multiple parameters. Like here:
```haskell
λ: data User = User { userFoo :: Double, userFollowers :: [User], userBar :: Either () (Maybe T.Text) } deriving Generic
λ: instance Elm User
λ: T.putStrLn $ prettyShowDefinition $ toElmDefinition (Proxy @User)
type alias User =
{ foo : Float
, followers : List User
, bar : Result () Maybe String
}
```
I propose to solve this pretty-printing problem under separate PR.
=> [#18] Support primitive elm types

src/Elm/Generic.hs
Resolves #29 
Now it works as expected. And it even works for some common cases of nested data structures (like list of `Id User` but I don't understand why it works).
=> [#29] Fix showing of types with type parameters

.ghci, src/Elm/Print.hs
=> Implement JSON encoders pretty print

.ghci, elm-street.cabal, src/Elm.hs, src/Elm/Generate.hs, src/Elm/Print.hs
=> [#8] Implement writing of elm code to files

src/Elm/Generate.hs, src/Elm/Print.hs
=> [#5] Implement decoders pretty printing

elm-street.cabal, src/Elm/Ast.hs, src/Elm/Generate.hs, src/Elm/Generic.hs, src/Elm/Print.hs
=> [#27] Support UTCTime data type

elm-street.cabal, generate-elm/Main.hs, src/Elm/Generate.hs
This is only a part of #33.
I've left directory with elm project and module hierarchy blank. Need to filled once we have scaffolded elm project. I also prettified output a little bit so now it contains proper amount of blank lines.
=> Implement executable to generate elm definitions

README.md, elm-example/.gitignore, elm-example/elm.json, elm-example/public/index.html, elm-example/public/manifest.json, elm-example/src/Core/Decoder.elm, elm-example/src/Core/ElmStreet.elm, elm-example/src/Core/Encoder.elm, elm-example/src/Core/Types.elm, elm-example/src/Main.elm, elm-example/src/index.js, elm-example/src/main.css, elm-example/src/registerServiceWorker.js, elm-example/tests/Tests.elm, generate-elm/Main.hs, src/Elm/Generate.hs, src/Elm/Print.hs
=> [#33] Create minimal elm project

elm-street.cabal, generate-elm/Main.hs, types/Types.hs
=> [#43] create internal library for types

src/Elm/Generic.hs
=> Add compile time errors for Generic deriving

README.md
=> [#51] Write README docs

elm-street.cabal, src/Elm.hs, src/Elm/Aeson.hs, src/Elm/Generic.hs, stack.yaml, types/Types.hs
=> [#53] Add custom Aeson options and helper functions

src/Elm/Aeson.hs, src/Elm/Generic.hs
=> [#48] Custom error for Sum typs with named fields

.travis.yml, elm-street.cabal, src/Elm/Aeson.hs, stack-8.4.4.yaml
=> [#61] Support 8.4.4 for Stack

src/Elm/Print.hs
=> [#64] Fix enum list indentation

CHANGELOG.md, README.md, elm-street.cabal, frontend/src/Core/Decoder.elm, frontend/src/Core/Encoder.elm, frontend/src/Core/Types.elm, src/Elm/Print.hs, types/Types.hs
Resolves #66 
Resolves #63 
I also improved documentation a little bit so it's more clear from the README how you should derive `FromJSON` and `ToJSON` instances for different data types.
=> [#66] Patch generated JSON encoders and decoders

.gitignore, CHANGELOG.md, elm-street.cabal, src/Elm/Aeson.hs
=> [#72] Fix Haskell JSON encoder for unary constructors

.travis.yml, CHANGELOG.md, Setup.hs, backend/Main.hs, elm-street.cabal, stack-8.4.4.yaml, stack.yaml
=> [#76] Modernise project

CHANGELOG.md, frontend/src/Core/Encoder.elm, src/Elm/Print.hs
Resolves #80
*Note:* I didn't add `tag` on decoders side as this is not necessary.
=> [#80] Fix 'key "tag" not present' issue

CHANGELOG.md, README.md
=> [#73] Adding documentation for reserved words in elm

CHANGELOG.md, elm-street.cabal, src/Elm/Generic.hs
=> [#71] Remove Elm instance for `String` data type

.travis.yml, frontend/tests/Tests.elm, test/golden/oneType.json
Add golden json file
Add Elm test CI check
I will try to implement other-direction test separately as I need the working link of the golden file to read it from Elm side.
=> [#79] Implement pure Elm tests

CHANGELOG.md, elm-street.cabal
Preparing for hackage release and testing the new CI at the same time :smile:
=> Bump to 0.1.0.4

.github/workflows/haskell-ci.yml, README.md, elm-street.cabal, frontend/elmapp.config.js, frontend/src/Api.elm, frontend/src/Core/Decoder.elm, frontend/src/Core/Encoder.elm, frontend/src/Core/Types.elm, frontend/src/Main.elm, frontend/tests/Tests.elm, frontend/tests/Tests/Golden.elm, src/Elm/Ast.hs, src/Elm/Generate.hs, src/Elm/Generic.hs, src/Elm/Print.hs, src/Elm/Print/Decoder.hs, src/Elm/Print/Encoder.hs, src/Elm/Print/Types.hs, stack.yaml, test/Test/Golden.hs, test/golden/oneType.json, types/Types.hs
An attempt to address https://github.com/Holmusk/elm-street/issues/111
=> Support Json.Decode.Value as primitive

src/Elm/Ast.hs, src/Elm/Generic.hs, src/Elm/Print.hs, src/Elm/Print/Decoder.hs, src/Elm/Print/Encoder.hs, src/Elm/Print/Types.hs, stack.yaml
Just a chore that should make it simpler to understand how to use ElmDefinition type.
It doesn't make sense to release this on its own. it should be batch with other improvements.
=> Rename alias to record

.github/workflows/haskell-ci.yml, CHANGELOG.md, elm-street.cabal, frontend/elm.json, frontend/tests/Tests/Golden.elm, src/Elm/Generic.hs, test/golden/oneType.json, types/Types.hs
Fix for https://github.com/Holmusk/elm-street/issues/122
=> Add overlapping instance for Elm String

elm-street.cabal
To address https://github.com/Holmusk/elm-street/issues/135
=> Include golden test file missing in cabal sdist

.github/workflows/haskell-ci.yml, elm-street.cabal, stack.yaml
Saw this trick in another repo, let's see if it works..
=> Simplify CI config by including latest rather than excluding non-latest

.github/workflows/haskell-ci.yml, CHANGELOG.md, elm-street.cabal, stack.yaml
https://github.com/commercialhaskell/stackage/issues/7287
=> Relax version bounds of warp, text and filepath
